Travis-CI depends on a TeX Live greater than 2009
Ubuntu Precise comes with TeX Live 2009, too old for the
latest TikZ Sphinx extension that will build PDF output
with the 'standalone' LaTeX document class.

Travis-CI should install all TeX Live packages from the
backport PPA.

Related to issue #1.

Fix:
sphinxcontrib.tikz.TikzExtError: Error (tikz extension):
                                 pdflatex exited with error:
[stderr]
b''
[stdout]
b"This is pdfTeX, Version 3.1415926-1.40.10 (TeX Live 2009/Debian)
entering extended mode
(./tikz.tex
LaTeX2e <2009/09/24>
Babel <v3.8l> and hyphenation patterns for english, usenglishmax, dumylang, noh
yphenation, loaded.

! LaTeX Error: File `standalone.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.3 \\usepackage
               [utf8]{inputenc}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on tikz.log.
"

Signed-off-by: Stephan Linz <linz@li-pro.net>