Travis-CI depends on a proper TikZ installation
Fix:
Traceback (most recent call last):
  File ".../.tox/py27-sphinx1.2/lib/python2.7/site-packages/sphinx_testing/util.py", line 142, in decorator
    func(*(args + (app, status, warning)), **kwargs)
  File "/home/travis/build/lipro/publishing-withsphinx/tests/test_basic.py", line 532, in test_build_html
    self.assertRegex(r, '<img\s+src=".*images\/tikz-.*\.svg"\s+alt="\[transform\s+shape,')
AssertionError: Regexp didn't match: '<img\\s+src=".*images\\/tikz-.*\\.svg"\\s+alt="\\[transform\\s+shape,' not found in u'...'

Signed-off-by: Stephan Linz <linz@li-pro.net>