Travis-CI depends on a proper PDF2SVG insatllation
Fix:
FileNotFoundError: [Errno 2] No such file or directory: 'pdf2svg'
sphinx.errors.SphinxWarning: WARNING: pdf2svg command cannot be run

Signed-off-by: Stephan Linz <linz@li-pro.net>